"""
CAD Translator - Build & Package Script
========================================
Creates a distributable Windows package:
  1. Self-contained folder with all dependencies
  2. Inno Setup installer script (for ISCC compilation)
  3. Portable ZIP for manual deployment

Usage:
    python build_installer.py          # Create all packages
    python build_installer.py --zip    # ZIP only (fast)
    python build_installer.py --iss    # Generate Inno Setup script only
"""
import os
import sys
import json
import shutil
import zipfile
import argparse
from pathlib import Path

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
BUILD_DIR = os.path.join(BASE_DIR, "build")
DIST_DIR = os.path.join(BASE_DIR, "dist")

# Files/dirs to include in the package
INCLUDE_PATTERNS = [
    "app.py",
    "updater.py",
    "start.bat",
    "version.json",
    "requirements.txt",
    "README.md",
    "backend/",
    "static/",
    "templates/",
    "fonts/",
    "data/glossary.json",
    "data/synonym_map.json",
]


def load_version() -> dict:
    with open(os.path.join(BASE_DIR, "version.json"), 'r', encoding='utf-8') as f:
        return json.load(f)


def create_build_folder():
    """Create a clean build folder with all required files."""
    ver = load_version()
    version_str = ver["version"]
    
    build_path = os.path.join(BUILD_DIR, f"CAD-Translator-v{version_str}")
    if os.path.exists(build_path):
        shutil.rmtree(build_path)
    
    os.makedirs(build_path, exist_ok=True)
    
    # Copy files
    for pattern in INCLUDE_PATTERNS:
        src = os.path.join(BASE_DIR, pattern)
        dst = os.path.join(build_path, pattern)
        
        if os.path.isdir(src):
            # Copy directory, skip __pycache__ and .pyc
            shutil.copytree(
                src, dst, ignore=shutil.ignore_patterns('__pycache__', '*.pyc', '*.db', '.git*')
            )
        elif os.path.isfile(src):
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            shutil.copy2(src, dst)
    
    # Create empty dirs needed at runtime
    for d in ['uploads', 'data/previews', 'data/output']:
        os.makedirs(os.path.join(build_path, d), exist_ok=True)
    
    # Copy Tesseract detection hint file
    tesseract_hint = os.path.join(build_path, "TESSERACT.txt")
    with open(tesseract_hint, 'w', encoding='utf-8') as f:
        f.write(
            "CAD Translator requires Tesseract OCR for raster PDF processing.\n"
            "Download: https://github.com/UB-Mannheim/tesseract/wiki\n"
            "Install with Chinese (chi_sim) and English (eng) language packs.\n"
        )
    
    print(f"Build folder created: {build_path}")
    return build_path


def create_zip_package(build_path: str) -> str:
    """Create a portable ZIP package."""
    ver = load_version()
    version_str = ver["version"]
    
    os.makedirs(DIST_DIR, exist_ok=True)
    zip_path = os.path.join(DIST_DIR, f"CAD-Translator-v{version_str}.zip")
    
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zf:
        for root, dirs, files in os.walk(build_path):
            # Skip data directories with large files
            dirs[:] = [d for d in dirs if d not in ('uploads', 'previews', 'output') 
                      or root.endswith('data')]
            for file in files:
                full_path = os.path.join(root, file)
                arcname = os.path.relpath(full_path, os.path.dirname(build_path))
                zf.write(full_path, arcname)
    
    size_mb = os.path.getsize(zip_path) / (1024 * 1024)
    print(f"ZIP package created: {zip_path} ({size_mb:.1f} MB)")
    return zip_path


def generate_iss_script(build_path: str) -> str:
    """Generate Inno Setup script for Windows installer."""
    ver = load_version()
    version_str = ver["version"]
    app_name = "CAD PDF Translator"
    
    iss_content = f"""; Inno Setup Script for CAD PDF Translator
; Generated by build_installer.py
; Compile with: iscc CAD-Translator-Setup.iss

#define MyAppName "{app_name}"
#define MyAppVersion "{version_str}"
#define MyAppPublisher "CAD Translator Team"
#define MyAppURL "https://github.com/15364/cad-translator"
#define MyAppExeName "start.bat"

[Setup]
AppId={{{{CAD-PDF-TRANSLATOR-2026}}}}
AppName={{#MyAppName}}
AppVersion={{#MyAppVersion}}
AppPublisher={{#MyAppPublisher}}
AppPublisherURL={{#MyAppURL}}
AppSupportURL={{#MyAppURL}}
AppUpdatesURL={{#MyAppURL}}
DefaultDirName={{pf32}}\\CAD Translator
DefaultGroupName={{#MyAppName}}
AllowNoIcons=yes
OutputDir={DIST_DIR}
OutputBaseFilename=CAD-Translator-Setup-v{version_str}
Compression=lzma
SolidCompression=yes
WizardStyle=modern
DisableProgramGroupPage=yes
PrivilegesRequired=admin

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "{build_path}\\*"; DestDir: "{{app}}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{{group}}\\{{#MyAppName}}"; Filename: "{{app}}\\start.bat"; WorkingDir: "{{app}}"
Name: "{{group}}\\Uninstall {{#MyAppName}}"; Filename: "{{uninstallexe}}"
Name: "{{commondesktop}}\\{{#MyAppName}}"; Filename: "{{app}}\\start.bat"; WorkingDir: "{{app}}"

[Run]
Filename: "{{app}}\\TESSERACT.txt"; Description: "View Tesseract installation guide"; Flags: postinstall shellexec

[Code]
function IsTesseractInstalled: Boolean;
begin
    Result := FileExists(ExpandConstant('{{pf32}}\\Tesseract-OCR\\tesseract.exe')) or
              FileExists(ExpandConstant('{{pf64}}\\Tesseract-OCR\\tesseract.exe'));
end;

function InitializeSetup: Boolean;
begin
    Result := True;
    if not IsTesseractInstalled then
    begin
        MsgBox('Tesseract OCR is not installed.' + #13#10 +
               'Please install Tesseract from https://github.com/UB-Mannheim/tesseract/wiki' + #13#10 +
               'with Chinese (chi_sim) and English (eng) language packs.' + #13#10#13#10 +
               'You can continue installation but raster PDF processing will be limited.',
               mbInformation, MB_OK);
    end;
end;
"""
    
    iss_path = os.path.join(DIST_DIR, "CAD-Translator-Setup.iss")
    os.makedirs(DIST_DIR, exist_ok=True)
    with open(iss_path, 'w', encoding='utf-8') as f:
        f.write(iss_content)
    
    print(f"Inno Setup script generated: {iss_path}")
    print(f"Compile with: iscc \"{iss_path}\"")
    return iss_path


def main():
    parser = argparse.ArgumentParser(description="CAD Translator Build Script")
    parser.add_argument("--zip", action="store_true", help="Create ZIP package only")
    parser.add_argument("--iss", action="store_true", help="Generate ISS script only")
    args = parser.parse_args()
    
    ver = load_version()
    print(f"Building CAD Translator v{ver['version']} (Build {ver['build']})")
    print("-" * 60)
    
    # Step 1: Create build folder
    build_path = create_build_folder()
    
    # Step 2: Package
    if args.iss:
        generate_iss_script(build_path)
    elif args.zip:
        create_zip_package(build_path)
    else:
        create_zip_package(build_path)
        generate_iss_script(build_path)
    
    print("-" * 60)
    print("Build complete!")
    print(f"Distributables in: {DIST_DIR}")
    
    # List dist contents
    for f in sorted(os.listdir(DIST_DIR)):
        fpath = os.path.join(DIST_DIR, f)
        size = os.path.getsize(fpath) if os.path.isfile(fpath) else 0
        print(f"  {f} ({size/1024:.0f} KB)")


if __name__ == "__main__":
    main()
